artifacts_root: artifacts


data_ingestion:
  local_data_file: artifacts/data_ingestion/PlantVillage.zip
  root_dir: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion
  data_name: "PlantVillage"
  
base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model_weights.pth
    updated_base_model_path: artifacts/prepare_base_model/base_model_updated_weights.pth

prepare_callbacks:
  root_dir: artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/callbacks/checkpoint_dir/model_weights.pth